name: my_learning_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.11.0-93.0.dev
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_analytics: ^12.0.4
  flutter_launcher_icons: ^0.14.4
  font_awesome_flutter: ^10.12.0
  google_fonts: ^6.3.2
  go_router: ^17.0.0
  google_sign_in: 5.4.4
  flutter_facebook_auth: ^7.1.2
  provider: ^6.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/appIcon.png"  
  adaptive_icon_background: "#FFFFFF" # Or an image path
  adaptive_icon_foreground: "assets/appIcon.png" # Or an image path
 
flutter:
  uses-material-design: true
  assets:
    - assets/appIcon.png
    - assets/appLogo.png
    - assets/loaderAnimation.gif
    - assets/userimage.png
 